apiVersion: v1
kind: ConfigMap
metadata:
  name: rental-api-config
  namespace: rental
data:
  CLIENT_URL: "http://ae3b0296de3e84446aba612ab8ecb1ea-817453542.us-east-1.elb.amazonaws.com"
  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_SAME_SITE: "lax"
